config/routes.rb
Microcommunity::Application.routes.draw do

  resources :comments

  post "group_follows/create"
  post "users_follows/create"
  post "memberships/create"

  resources :posts

  resources :groups do
    resources :posts
  end

  resources :attendances

  resources :questions

  resources :wikipages
  resources :profiles
  resources :events do
  	resources :attendances
  end

  root :to => 'pages#home'
  match "home" => "pages#home"
  match "home" => "pages#home"

  match "questions" =>"questions"

  devise_for :users, :controllers => { :registrations => "registrations" }

end

app/models/wikipage.rb
class Wikipage < ActiveRecord::Base
  belongs_to :user
  has_many :revisions

  acts_as_followable
  
  validates :title, :presence => true
  validates :body, :presence => true
  
  has_many :activities, :as => :action_object
  
end

app/controllers/wikipages_controller.rb
class WikipagesController < ApplicationController
  # GET /wikipages
  # GET /wikipages.json
  def index
    @wikipages = Wikipage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @wikipages }
    end
  end

  # GET /wikipages/1
  # GET /wikipages/1.json
  def show
    @wikipage = Wikipage.find(params[:id])
    @history =  Activity.where(
      :action_object_id => @wikipage.id,
      :action_object_type => "Wikipage"
    ).order("updated_at DESC")

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @wikipage }
      format.js
    end
  end

  # GET /wikipages/new
  # GET /wikipages/new.json
  def new
    @wikipage = Wikipage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @wikipage }
    end
  end

  # GET /wikipages/1/edit
  def edit
    @wikipage = Wikipage.find(params[:id])
    respond_to do |format|
      format.html
      format.js { render :layout => false }
    end
  end

  # POST /wikipages
  # POST /wikipages.json
  def create
    @wikipage = Wikipage.new(params[:wikipage])
    @wikipage.user_id = current_user.id

    if @wikipage.save
      if params.has_key?(:group_id)
        @group = Group.find(params[:group_id])
        @group.follow(@wikipage)
      end
    end

    respond_to do |format|
      unless @wikipage.new_record?
        format.html { redirect_to :back, notice: 'Wikipage was successfully created.' }
        format.json { render json: @wikipage, status: :created, location: @wikipage }
      else
        format.html { render action: "new" }
        format.json { render json: @wikipage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /wikipages/1
  # PUT /wikipages/1.json
  def update
    @wikipage = Wikipage.find(params[:id])


    respond_to do |format|
      if @wikipage.update_attributes(params[:wikipage])
        format.html { redirect_to @wikipage, notice: 'Wikipage was successfully updated.' }
        format.js {@update_activity = Activity.last}
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @wikipage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wikipages/1
  # DELETE /wikipages/1.json
  def destroy
    @wikipage = Wikipage.find(params[:id])
    @wikipage.destroy

    respond_to do |format|
      format.html { redirect_to wikipages_url }
      format.json { head :ok }
    end
  end
end

app/helpers/wikipages_helper.rb
module WikipagesHelper
end

app/views/wikipages/_form.html.haml
- if @wikipage.errors.any?
	#error_explanation{:class => "alert alert-error row"}
		%p
			= pluralize(@wikipage.errors.count, "error")
			prohibited this wikipage from being saved:
		%ul
			- @wikipage.errors.full_messages.each do |msg|
				%li
					= msg

.clearfix
	= f.label :title, t("activerecord.attributes.wikipage.title", :default => "Title"), :class => :label
	.input
		= f.text_field :title, :class => 'text_field'
.clearfix
	= f.label :body, t("activerecord.attributes.wikipage.body", :default => "Body"), :class => :label
	.input
		= f.text_area :body, :class => 'text_area', :class => "span12", :rows => "15"
	.input
		= f.hidden_field :user_id, :class => 'number_field'
	- unless @group.nil?
		.input
			= hidden_field_tag :group_id, @group.id,:class => 'number_field'

.form-actions
	%button{:class => "btn primary", :type => "submit"} Save
	or
	= link_to "Cancel", wikipages_path

app/views/wikipages/_modal_form.html.haml
.modal.hide.fade#wiki-modal
	.modal-header
		%a.close{"data-dismiss"=>"modal"}
			×
		%h3 New wikipage
	.modal-body
		- @wikipage = Wikipage.new
		= form_for @wikipage, :url => wikipages_path, :html => { :class => :form } do |f|
			.clearfix
				= f.label :title, t("activerecord.attributes.wikipage.title", :default => "Title"), :class => :label
				.input
					= f.text_field :title, :class => 'text_field'
			.clearfix
				= f.label :body, :class => :label
				.input
					= f.text_area :body, :class => 'text_area',  :rows => "10", :cols => "80"
				.input
					= f.hidden_field :user_id, :class => 'number_field'
				- unless @group.nil?
					.input
						= hidden_field_tag :group_id, @group.id,:class => 'number_field'
			.modal-footer
				%a.btn{"data-dismiss"=>"modal"} Cancel
				%button{:class => "btn btn-primary", :type => "submit"} Save changes

app/views/wikipages/_remote_form.html.haml
- if @wikipage.errors.any?
	#error_explanation{:class => "alert alert-error row"}
		%p
			= pluralize(@wikipage.errors.count, "error")
			prohibited this wikipage from being saved:
		%ul
			- @wikipage.errors.full_messages.each do |msg|
				%li
					= msg

.clearfix
	.input
		= f.text_area :body, :class => 'text_area span4',  :rows => "10", :cols => "80"
	.input
		= f.hidden_field :user_id, :class => 'number_field'
	- unless @group.nil?
		.input
			= hidden_field_tag :group_id, @group.id,:class => 'number_field'

.form-actions
	%button{:class => "btn btn-primary", :type => "submit"} Save

app/views/wikipages/_wikipage.html.haml
#wikipage.well
	- if user_signed_in?
		= button_to "Edit", edit_wikipage_path(wikipage), :method => "get", :form_class => "remote-wikipage-link", :class => 'btn btn-success pull-right', :remote => true, :id => "wikipage-edit-button"
	- else
		%button.btn.btn-success.pull-right.disabled Sign in to edit
	.page-header
		%h1= wikipage.title
	#wikipage-body
		%p= simple_format wikipage.body

app/views/wikipages/edit.html.haml
= form_for @wikipage, :url => wikipage_path(@wikipage), :html => { :class => "edit_wikipage", :id => "edit_wikipage" } do |f|
  %input{:name => "_method", :type => "hidden", :value =>"put"}
  = render :partial => "form", :locals => {:f => f}

app/views/wikipages/edit.js.erb
$("#wikipage-edit-button").hide();
$("#wikipage").prepend("<%= escape_javascript(button_to("Cancel", {:controller => 'wikipages', :action => 'show', :id => @wikipage.id }, :method => "get", :remote => true, :class => "pull-right btn btn-danger")) %>");

$("#wikipage-body").html("<%= escape_javascript(render :template => "wikipages/remote_edit.html") %>");

app/views/wikipages/index.html.haml
%h1 Wikipages
%table{:class => "table table-striped"}
  %thead
    %tr
      %th ID
      %th
        = t("activerecord.attributes.wikipage.body", :default => t("activerecord.labels.body", :default => "Body"))
      %th Created at
      %th Actions
  %tbody
    - @wikipages.each do |wikipage|
      %tr
        %td= wikipage.id
        %td= link_to wikipage.title, wikipage_path(wikipage)
        %td= wikipage.created_at
        %td
          = link_to "Edit", edit_wikipage_path(wikipage)

= link_to "New", new_wikipage_path, :class => 'btn btn-primary'

app/views/wikipages/new.html.haml
= form_for @wikipage, :url => wikipages_path, :html => { :class => :form } do |f|
  = render :partial => "form", :locals => {:f => f}

app/views/wikipages/new.js.erb
$('.modal-body').html('<%= escape_javascript(render :partial => 'form') %>');
$('.modal-header').remove(); // don't need a header here

app/views/wikipages/remote_edit.html.haml
= form_for @wikipage, :remote => true, :url => wikipage_path(@wikipage), :html => { :class => "edit_wikipage", :id => "edit_wikipage" } do |f|
  %input{:name => "_method", :type => "hidden", :value =>"put"}
  = render :partial => "remote_form", :locals => {:f => f}

app/views/wikipages/show.html.haml
.row
	.span9
		.row.page-header
			.span6
				%h1= @wikipage.title

			.span3
				%ul.nav.nav-pills.pull-right
					%li.dropdown
						:plain
							<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
								Add/Remove
								<b class="caret"></b>
							</a>
						- unless current_user.nil?
							#add-to-group
								%ul.dropdown-menu
									- current_user.groups.each do |group|
										%li
											- params = {:controller => 'group_follows', :action => 'create', :group_id => group.id, :user_id => current_user.id, :content_type => @wikipage.class.to_s, :content_id => @wikipage.id }
											= link_to( params, {:method => :post},:id => "group-#{group.id}") do
												-if group.following?(@wikipage)
													%i.icon-ok
												= group.name

					%li= link_to "Back", :back, :class => 'btn'
					%li= link_to "Edit", edit_wikipage_path(@wikipage), :class => 'btn'
		.row
			.span9
				%p= @wikipage.body

	.span3#content-stream
		%table.table.table-condensed#content-stream-table
			- @history.each do |activity|
				= render :partial => "activities/activity", :locals => { :activity => activity, :is_remote => true }

app/views/wikipages/show.js.erb
$("#content-canavas").html("<%= escape_javascript(render @wikipage) %>");

app/views/wikipages/update.js.erb
$("#content-canavas").html("<%= escape_javascript(render @wikipage) %>");

$("#content-stream-table").prepend("<%= escape_javascript(render(:partial => "activities/activity", :object => @update_activity, :locals => {:is_remote => true})) %>");