config/routes.rb
Microcommunity::Application.routes.draw do

  resources :comments

  post "group_follows/create"
  post "users_follows/create"
  post "memberships/create"

  resources :posts

  resources :groups do
    resources :posts
  end

  resources :attendances

  resources :questions

  resources :wikipages
  resources :profiles
  resources :events do
  	resources :attendances
  end

  root :to => 'pages#home'
  match "home" => "pages#home"
  match "home" => "pages#home"

  match "questions" =>"questions"

  devise_for :users, :controllers => { :registrations => "registrations" }

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :memberships
  has_many :users, :through => :memberships

  has_many :posts, :as => :owner

  acts_as_follower

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])
    @post = @group.posts.new
    @group_activity = Activity.where(
      :action_object_id => @group.id,
      :action_object_type => @group.class.to_s,
    ).order("updated_at DESC")

    @group_wikipages = @group.following_wikipages
    @group_wikipages_ids = @group_wikipages.map do |wikipage|
      wikipage.id
    end

    @content_stream = Activity.where(
      :action_object_id => @group_wikipages_ids,
      :action_object_type => "Wikipage"
    ).order("updated_at DESC")

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])
    @group.save

    @group.memberships.create(:user_id => User.current_user.id, :admin => true)

    respond_to do |format|
      unless @group.new_record?
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :ok }
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.haml
.clearfix
  = f.label :name, t("activerecord.attributes.group.name", :default => "Name"), :class => :label
  .input
    = f.text_field :name, :class => 'text_field'
.clearfix
  = f.label :description, t("activerecord.attributes.group.description", :default => "Description"), :class => :label
  .input
    = f.text_area :description, :class => 'text_area'

.form-actions
  %button{:class => "btn primary", :type => "submit"} Save
  or
  = link_to "Cancel", groups_path

app/views/groups/_group.html.haml
.well
	%h2= link_to group.name, group_path(group)
	%p= group.description
	%p
		%table.pull-right
			%tr
				- unless current_user.nil?
					- unless group.users.include?(current_user)
						%td
							- params = {:controller => 'memberships', :action => 'create', :membership => {:group_id => group.id, :user_id => current_user.id} }
							= button_to "Join", params, :class => "btn btn-primary", :id => "join-group"
				%td= button_to "View", group_path(group), :class => 'btn', :method => :get

app/views/groups/_modal_form.html.haml
.modal.hide.fade#wiki-modal
	.modal-header
		%a.close{"data-dismiss"=>"modal"}
			×
		%h3 New wikipage
	.modal-body
		- @wikipage = Wikipage.new
		= form_for @wikipage, :url => wikipages_path, :html => { :class => :form } do |f|
			.clearfix
				= f.label :name
				.input
					= f.text_field :name, :class => 'text_field'
			.clearfix
				= f.label :description, t("activerecord.attributes.group.description", :default => "Description"), :class => :label
				.input
					= f.text_area :description, :class => 'text_area'

			.form-actions
				%button{:class => "btn primary", :type => "submit"} Save
				or
				= link_to "Cancel", groups_path
	.modal-footer
		%a.btn Close
		%a.btn.btn-primary Save changes

app/views/groups/edit.html.haml
= form_for @group, :url => group_path(@group), :html => { :class => "edit_group", :id => "edit_group" } do |f|
  %input{:name => "_method", :type => "hidden", :value =>"put"}
  = render :partial => "form", :locals => {:f => f}

app/views/groups/index.html.haml
.row
	.span12
		.page-header
			.row
				.span8
					%h1 Groups
				.span4
					= link_to "Create a group",new_group_path ,:class => "btn btn-large pull-right"


.row
	- @groups.each do |group|
		.span4
			= render group

app/views/groups/new.html.haml
= form_for @group, :url => groups_path, :html => { :class => :form } do |f|
  = render :partial => "form", :locals => {:f => f}

app/views/groups/show.html.haml
.row.page-header
	.span9
		%h1
			= @group.name
		%p
			= @group.description
	.span3
		- unless current_user.nil?
			- unless @group.users.include?(current_user)
				- params = {:controller => 'memberships', :action => 'create', :membership => {:group_id => @group.id, :user_id => current_user.id} }
				= button_to "Join", params, :class => "btn btn-primary btn-large pull-right", :id => "join-group"

.row
	.span4#social-stream
		- if @group.users.include?(current_user)
			#group-publisher
				= form_for @post, :remote => true do |f|
					%p
						= f.text_area :text,  :class => "span4", :rows => 1, :id => "group-publisher-text", :placeholder => "Write something..."
						= f.hidden_field :user_id, :class => 'number_field', :value => current_user.id
						= f.hidden_field :owner_type, :value => @group.class.to_s
						= f.hidden_field :owner_id, :value => @group.id
						.row
							.span4.post-button
								= f.submit("Post", :class => "btn btn-success pull-right", :id => "post-button")

		- unless @group.posts.empty?
			%table.table.table-condensed#social-stream-table
				= render @group.posts.order("created_at DESC") + @group_activity

	.span5#content-canavas
		- unless @content_stream.first.nil?
			= render @content_stream.first.action_object
		- else
			.well
				You currently have no content! You can simply create one by hitting the button on the right!
			- if @group.posts.count > 1
				= render :partial => "posts/embeded_post", :object => @group.posts.order("created_at DESC").first

	.span3#content-stream
		- unless current_user.nil?
			- if @group.users.include?(current_user)
				%ul.nav.pull-right
					%button.btn.btn-primary{"data-toggle"=>"modal", :href => "#wiki-modal"}
						%i.icon-file
						Wikipage
					%button.btn.btn-primary.disabled
						%i.icon-question-sign
						Question

		- if @content_stream.nil?
			%p You currently have no content. To post new content pick one above
		- else
			%table.table.table-condensed#content-stream-table
				- @content_stream.each do |activity|
					= render :partial => "activities/activity", :locals => { :activity => activity, :is_remote => true }

= render "wikipages/modal_form"